### ISSUE TITLE
Do a JavaScript release

### ISSUE THREAD

**Issue by znewman01** [sigstore/protobuf-specs#61] opened 2023-01-19 14:29 UTC
See #3.

This would entail:

- setting up an npm project for this repo
- automating the procedure to generate JS bindings to the protos (`Makefile`), generally checking in the generated code (`gen/` and `.github/workflows/`)
- automating/documenting the procedure to do releases of the generated code (`RELEASE.md` plus any GH Actions) on a tag, preferably `releases/js/v0.1.1` or whatever.

Then you could start consuming it in sigstore-js.

 CC @bdehamer @feelepxyz @eddiezane

**Comment by vlsi** [comment] 2023-01-23 09:13
Can we refrain from checking in the generated code?

It makes contributions hard as it enforced everybody to install all the tools, and sometimes it causes checking in **binary** code like in https://github.com/sigstore/protobuf-specs/blob/16541696de137c6281d66d075a4924d9bbd181ff/gen/pb-go/bundle/v1/sigstore_bundle.pb.go#L308-L329

**Comment by znewman01** [comment] 2023-01-23 11:16
I argued for exactly that in https://github.com/sigstore/protobuf-specs/pull/12 but was outvoted. The main issue is that Go kinda requires it :( I'd prefer not to reopen that can of worms. CC @asraa @kommendorkapten @woodruffw for visibility though

If it's substantially more idiomatic we can skip for JS; we already skip it for Java.

That said, the only tooling really needed here seems to be [Docker and make](https://github.com/sigstore/protobuf-specs/blob/main/Makefile);  are you having issues with those?

**Comment by vlsi** [comment] 2023-01-23 11:18
> The main issue is that Go kinda requires it

Can Go store the generated source into a `release` branch then?

Frankly speaking, it is annoying that PRs like https://github.com/sigstore/protobuf-specs/pull/64 require updating and committing generated code along with the changes themselves.

**Comment by woodruffw** [comment] 2023-01-24 02:58
I'm willing to change my opinion, but I'm still a soft 👎 on removing checked-in codegen for Python: it's relatively idiomatic to do so, and shouldn't have any significant developer burden (since as @znewman01 mentioned everything should be Dockerized).

I haven't run into any significant issues with either Go or Python's codegen, despite having some issues with Fulcio's similar codegen (which is *not* Dockerized).

**Comment by kommendorkapten** [comment] 2023-01-24 08:04
I think it makes sense to keep as-is, as we get to exercise the codegen frequently to avoid any hiccups during a planned release. And as already said, it's dockerized so it should be of minimal extra burden for a contributer (albeit I understand that it's easy to forget to run the code generation and so get some possible unexpected failures).

**Comment by vlsi** [comment] 2023-01-24 08:25
> codegen for Python: it's relatively idiomatic to do so

It thought Python was using pypi or something like that rather than fetching dependencies from the source code.

>I haven't run into any significant issues with either Go or Python's codegen

I wasn't able to get `make` to work: https://github.com/sigstore/protobuf-specs/pull/64#issuecomment-1400201925
I might need to try harder, however, previously, `docker` worked for me.

I see how checking in the generated code might be helpful in case the generator is complicated to set up.
For instance, suppose there's a "database engine" project, and it might have a generated SQL parser. Suppose, the parser generator is not available on all the platforms, so it might help if the generated parser was committed under source control, so everybody can work on the database without spending time on installing the generator.

On the other hand, `sigstore/protobuf-specs` does not fit that pattern. The only purpose of the repository is to collect `.proto` files, and there is no other business logic.

I am not sure I want to install toolchains (even in Docker) for all the ecosystems. It is more-or-less fine when `make` fetches docker images for `go` and `python` only, however, I am afraid it will go wild as the number of generators increases: `go`, `python`, `javascript`, `rust`, `java`, `clojure`, `haskell`, `c#`, `elm`, you name it.
I would refrain from invoking a build that downloads and installs all those dependencies, especially, when the only thing I want is to fix a typo in the proto definition and/or add an annotation.

**Comment by vlsi** [comment] 2023-01-26 16:51
>1. It reduces the likelihood of codegen errors and regressions: a regression in of protoc or betterproto can't result in us silently publishing a broken package

I do not see how committing the generated code prevents regressions.
I can easily see how running tests with the newly generated code could prevent regressions, however, committing the generated code does not make it tremendously better.

>2. It matches "publish what you know": someone who reports a bug in the Python bindings can send us a permalink to the exact line that's causing the error, without having to share their own copy of the generated code.

If you want something for documentation purposes, then it might live on a documentation branch/repository.

**Closed** 2023-02-18 14:55 UTC
Labels: enhancement
