### ISSUE TITLE
Keep version numbers consistent across languages

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/protobuf-specs#26] opened 2022-11-22 05:09 UTC
This repository is eventually going to contain code to publish packages to each language ecosystem's respective package index. We need to figure out some scheme of keeping these version numbers consistent. So for instance, the v0.0.5 version of this package should be generated from the same set of Protobuf specifications regardless of whether we download it for Python, Java, etc.

Context: https://github.com/sigstore/protobuf-specs/pull/25#discussion_r1028498032

**Comment by znewman01** [comment] 2022-11-22 14:08
Thanks for filing! I'm going to mark as a dupe of #22 (and drop a comment over there) to keep the work in one place.

**Closed by znewman01** 2022-11-22 14:08 UTC
Labels: duplicate, enhancement
